### ISSUE TITLE
Add pictures

### ISSUE THREAD

**Issue by mvorisis** [278204/GooeySlider#1]
Can we add images instead a colorful ball?

Many thanks for this awesome repo!!

**Comment by palforsberg** [comment]
It is, unfortunately, not possible in the projects current state. What sort of images do you have in mind?

**Comment by mvorisis** [comment]
Hi I put this question to stack too and someone referred me to another question which was about adding images to layers. So I put this line `gooey.contents = UIImage(named: "wash.png")?.cgImage`  to GooeyView inside init and it worked. (not in the correct size and as it is inside init its only at the first circle. (I'm thinking of images same size as the red circle that you have).

**Comment by palforsberg** [comment]
if you append an image of what you'd like the slider to look like I could take a look at it.

**Comment by mvorisis** [comment]
![untitled](https://cloud.githubusercontent.com/assets/18750097/20272568/fb73c826-aa96-11e6-97a2-3a9eda174abd.png)

Don't mind the space between the image and the label.
Thank you for your time I appreciate it!
